# @name get-prompt
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="teste.mp3"
Content-Type: audio/mpeg

< ./audio.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription

POST http://localhost:3333/videos/e89b569b-0744-499f-b814-8512596b9983/transcription
Content-Type: application/json

{
    "prompt": "biceps"
}

###

# @name generate-ai-completion

POST http://localhost:3333/ai/complete
Content-Type: application/json

{
    "videoId": "0074605e-c534-47be-a2a0-ef161ac8a593",
    "temperature": 0.5,
    "prompt": "Gere um resumo sucinto da transcrição do video informada a seguir: '''{transcription}'''"
}